import { Platform, StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { DayTheme } from "../../Constants/theme";
import Scaler from "../../Utils/Scaler";

const commonStyle = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  languageButton: {
    alignSelf: "center",
    borderRadius: Scaler(12),
    backgroundColor: "#fff",
    borderWidth: Scaler(1.5),
    // width: wp("85%"),
    // height: hp("8%"),
    width: wp(92),
    height: Scaler(60),
  },
  selectLanguageStyle: {
    marginHorizontal: Scaler(27),
    fontSize: Scaler(28),
    width: wp(60),
    marginTop: Scaler(100),
    color: DayTheme.colors.textBlack,
    ...DayTheme.fonts.medium,
  },
  headingStyle: {
    fontSize: Scaler(15),
    color: "grey",
    ...DayTheme.fonts.medium,
    marginHorizontal: Scaler(27),
  },
  submitButton: {
    backgroundColor: DayTheme.colors.primary,
    width: wp("70%"),
    height: hp("6.5%"),
    bottom: Scaler(80),
  },
  tittleStyle: {
    fontSize: Scaler(34),
    color: DayTheme.colors.textBlack,
    ...DayTheme.fonts.medium,
    lineHeight: Scaler(42),
  },
  inputChangeStyle: {
    fontSize: Scaler(13),
    color: DayTheme.colors.textBlack,
    ...DayTheme.fonts.medium,
  },
  clickHereStyle: {
    fontSize: Scaler(13),
    color: DayTheme.colors.primary,
    ...DayTheme.fonts.medium,
  },
  accountsStyle: { flexDirection: "row" },
  continueStyle: {
    fontSize: Scaler(14),
    color: DayTheme.colors.textBlack,
    ...DayTheme.fonts.medium,
  },
  textColorStyle: {
    fontSize: Scaler(14),
    color: DayTheme.colors.primary,
    textDecorationLine: "underline",
    ...DayTheme.fonts.medium,
  },
  interestCountStyle: {
    textAlign: "right",
    left: Scaler(40),
    top: Scaler(5),
    ...DayTheme.fonts.medium,
    color: "#000",
  },
  imageArrowStye: { width: wp(5), height: hp(5), right: Scaler(20) },
  textLanguageSetStyle: {
    width: wp(25),
    height: hp(4),
    alignSelf: "center",
    left: Scaler(20),
  },
  tittleLanguageStyle: {
    color: DayTheme.colors.textBlack,
    fontSize: 20,
    ...DayTheme.fonts.medium,
  },
  logoStyle: { alignSelf: "center", width: wp(50), height: hp(15), top: hp(2) },
  notificationiconStyle: { width: wp(18), height: hp(7) },
  BorderWidthStyle: {
    borderWidth: 0.5,
    borderColor: "#CECECE",
    top: Scaler(-10),
  },
  trendingProfileStyle: { width: wp(8.3), height: hp(4) },
  viewAllTextStyle: {
    fontSize: Scaler(12),
    color: DayTheme.colors.primary,
    textAlign: "center",
    top: 10,
    ...DayTheme.fonts.medium,
  },
  viewTouchStyle: {
    backgroundColor: "#EEEBFF",
    width: wp(27),
    borderRadius: Scaler(10),
    overflow: "hidden",
    height: Scaler(38),
    alignSelf: "flex-end",
    top: Platform.OS === "ios" ? hp(-0.2) : 0,
  },
  trendingTittleViewStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: Scaler(20),
    marginTop: Scaler(20),
  },
  tittleTextFieldStyle: {
    fontSize: Scaler(18),
    ...DayTheme.fonts.medium,
    color: "#000",
  },
  timeTextStyle: {
    textAlign: "right",
    fontSize: Scaler(12),
    color: "#7F8190",
    width: wp(28),
    alignSelf: "flex-end",
    right: Scaler(20),
    fontFamily: "Poppins-Regular",
    top: hp(0.2),
  },
  nameTextStyle: {
    top: hp(2),
    width: wp(70),
    left: wp(1.9),
    fontSize: Scaler(15),
    fontFamily: "Poppins-SemiBold",
    color: DayTheme.colors.textBlack,
  },
  departmentTextStyle: {
    left: wp(14.2),
    top: hp(-6),
    color: "#7F8190",
    fontSize: Scaler(12),
    ...DayTheme.fonts.medium,
  },
  rollTextStyle: {
    color: "#fff",
    fontSize: Scaler(12),
    textAlign: "center",
    ...DayTheme.fonts.regular,
  },

  playiconStyle: {
    width: 50,
    height: 50,
    alignSelf: "center",
    flex: 1,
    top: 20,
  },
  tittleContentStyle: {
    borderRadius: 7,
    overflow: "hidden",
    backgroundColor: "#EEEBFF",
    alignSelf: "flex-end",
    fontSize: Scaler(12),
    right: Scaler(20),
    color: DayTheme.colors.primary,
    top: hp(0.8),
    paddingHorizontal: wp(2),
    height: hp(3),
    textAlign: "center",
    fontFamily: "Poppins-Regular",
  },
  likeTextStyle: {
    fontSize: Scaler(15),
    left: Scaler(1),
    alignSelf: "center",
    ...DayTheme.fonts.medium,
  },
  commentTextStyle: {
    alignSelf: "center",
    left: Scaler(1),
    fontSize: Scaler(15),
    ...DayTheme.fonts.medium,
  },
  contentTextStyle: {
    color: "#000",
    marginHorizontal: Scaler(15),
    fontSize: Scaler(15),
    ...DayTheme.fonts.medium,
    width: wp(85),
    left: wp(3),
    top: hp(-0.5),
  },
  viewCardStyle: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 0.1,
    elevation: 5,
    backgroundColor: "#fff",
    borderRadius: 10,
    alignSelf: "center",
    flex: 1,
    width: wp(40),
    marginHorizontal: wp(4),
    marginVertical: hp(2),
  },
  pointCardStyle: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 0.1,
    elevation: 5,
    borderRadius: 10,
    width: "90%",
    height: hp(15),
    marginHorizontal: wp(4),
    marginVertical: hp(2),
  },
  reputationImgStyle: {
    marginVertical: hp(8),
    height: 90,
    width: 90,
    borderRadius: 45,
    borderColor: "#EEEBFF",
    borderWidth: 6,
  },
  reputationNameStyle: {
    textAlign: "center",
    fontFamily: "Poppins-SemiBold",
    color: DayTheme.colors.textBlack,
    fontSize: 20,
    marginVertical: hp(1),
  },
  reputationPointStyle: {
    textAlign: "center",
    fontFamily: "Poppins-SemiBold",
    color: DayTheme.colors.primary,
    fontSize: 15,
    backgroundColor: "#EEEBFF",
    padding: 5,
    width: wp(30),
    borderRadius: 10,
    overflow: "hidden",
    right: wp(4),
  },
  reputationiconStyle: { width: 78, height: 78, alignSelf: "center" },
  inputEditStyle: {
    width: wp(85),
    height: hp(6.5),
    borderColor: "#a9a9a9",
    borderWidth: 0.8,
    borderRadius: Scaler(10),
    alignSelf: "center",
  },
  designationEditStyle: {
    width: wp(85),
    borderColor: "#a9a9a9",
    borderWidth: 0.2,
    borderRadius: Scaler(10),
    overflow: "hidden",
    alignSelf: "center",
  },
  commenticonStyle: { width: wp(13), height: hp(5.2) },
  typeInboxStyle: {
    backgroundColor: "#fff",
    width: wp(100),
    height: hp(10),
    elevation: 5,
    borderTopWidth: 0.5,
    borderTopColor: "#ffff",
    shadowColor: "#000000",
    shadowOpacity: 0.8,
    shadowRadius: 4,
    shadowOffset: { height: 1, width: 1 },
    justifyContent: 'center',
  },
  inboxProfileiconStyle: {
    height: Scaler(60),
    width: Scaler(60),
    alignItems: "center",
    borderRadius: Scaler(30),
  },
  textInputStyle: {
    backgroundColor: "#F8F9F9",
    width: wp(65),
    borderRadius: 10,
    color: "#7F8190",
    left: wp(2),
    padding: 10,
  },
  settingiconStyle: { width: wp(15), height: hp(6) },
  settingTextStyle: {
    left: wp(3.5),
    fontSize: Scaler(18),
    fontFamily: "Poppins-SemiBold",
    color: "#000",
  },
  settingTouchStyle: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    width: wp(90),
    top: 10,
  },
});

export default commonStyle;
