export const UPDATE_SURVEY = "UPDATE_SURVEY";
export const UPDATE_SURVEY_QA = "UPDATE_SURVEY_QA";
export const DELETE_SURVEY_QA = "DELETE_SURVEY_QA";
export const UPDATE_PERSONAL_COMMUNITY = "UPDATE_PERSONAL_COMMUNITY";